

--장바구니
DROP TABLE C_CART;
CREATE TABLE C_CART(
    CARTNO NUMBER PRIMARY KEY,
    CVALIDATE NUMBER,  -- validate 0이 미구매(카트에서 보여줄것), 1이 구매완료
    CSIZE VARCHAR2(3),
    MID VARCHAR2(20),
    PNO NUMBER,
    CARTQUANTITY NUMBER,
    CONSTRAINT CART_MEMBER_FK FOREIGN KEY (MID) REFERENCES C_MEMBER (MID),
    CONSTRAINT CART_PRODUCT_FK FOREIGN KEY (PNO) REFERENCES C_PRODUCT (PNO)
);

DELETE FROM C_CART;
SELECT * FROM C_CART;

DROP SEQUENCE C_CART_SEQ;
CREATE SEQUENCE C_CART_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCACHE
NOCYCLE;




