

SELECT * FROM C_MEMBER;
CREATE TABLE C_MEMBER(
    MNO NUMBER PRIMARY KEY,
    MID VARCHAR2(20) UNIQUE NOT NULL,
    MNAME VARCHAR2(100),
    MPW VARCHAR2(50) NOT NULL,
    MMOBILE1 CHAR(3),
    MMOBILE2 CHAR(4),
    MMOBILE3 CHAR(4),
    MEMAIL VARCHAR2(50) UNIQUE NOT NULL,
    MBIRTH CHAR(6),
    MPOST VARCHAR2(20),
    MADDR1 VARCHAR2(100),
    MADDR2 VARCHAR2(100),
    MADDR3 VARCHAR2(100),
    MREGDATE DATE
);

INSERT INTO C_MEMBER (MNO, MID, MNAME, MPW, MMOBILE1, MMOBILE2, MMOBILE3, MEMAIL, MBIRTH, MPOST, MADDR1, MADDR2, MADDR3, MREGDATE)
		VALUES (C_MEMBER_SEQ.NEXTVAL, 'user', '사용자', 1111, '010', '1111', '1111', 'user@user.com', '000101', '100-100', '서울시 마포구', '무슨동', '100번지', SYSDATE);


DROP SEQUENCE C_MEMBER_SEQ;
CREATE SEQUENCE C_MEMBER_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCACHE
NOCYCLE;


--장바구니

DROP TABLE C_CART;
CREATE TABLE C_CART(
    CARTNO NUMBER PRIMARY KEY,
    CVALIDATE NUMBER,  -- validate 0이 미구매(카트에서 보여줄것), 1이 구매완료
    CSIZE VARCHAR2(3),
    MID VARCHAR2(20),
    PNO NUMBER,
    CARTQUANTITY NUMBER,
    CONSTRAINT CART_MEMBER_FK FOREIGN KEY (MID) REFERENCES C_MEMBER (MID),
    CONSTRAINT CART_PRODUCT_FK FOREIGN KEY (PNO) REFERENCES C_PRODUCT (PNO)
);

DELETE FROM C_CART;
SELECT * FROM C_CART;
INSERT INTO C_CART (CARTNO, CVALIDATE, CSIZE, MID, PNO, CARTQUANTITY) VALUES (C_CART_SEQ.NEXTVAL, 0, 'S', 'user', 10000, 2);
INSERT INTO C_CART (CARTNO, CVALIDATE, CSIZE, MID, PNO, CARTQUANTITY) VALUES (C_CART_SEQ.NEXTVAL, 1, 'M', 'user', 10001, 3);
SELECT * FROM C_PRODUCT;

DROP SEQUENCE C_CART_SEQ;
CREATE SEQUENCE C_CART_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCACHE
NOCYCLE;

--주문
DROP TABLE C_ORDER;
CREATE TABLE C_ORDER(
    ONO NUMBER PRIMARY KEY,
    MID VARCHAR2(20),
    ONAME VARCHAR2(100),
    OMOBILE1 CHAR(3),
    OMOBILE2 CHAR(4),
    OMOBILE3 CHAR(4),
    OEMAIL VARCHAR2(50),
    OPOST VARCHAR2(20),
    OADDR1 VARCHAR2(100),
    OADDR2 VARCHAR2(100),
    OADDR3 VARCHAR2(100),
    ODATE DATE,
    CARTNO NUMBER,
    CONSTRAINT ORDER_CART_FK FOREIGN KEY (CARTNO) REFERENCES C_CART (CARTNO),
    CONSTRAINT ORDER_MEMBER_FK FOREIGN KEY (MID) REFERENCES C_MEMBER (MID)
);


DROP SEQUENCE C_ORDER_SEQ;
CREATE SEQUENCE C_ORDER_SEQ
START WITH 10000
INCREMENT BY 1
MAXVALUE 999999
NOCACHE
NOCYCLE;

SELECT C.*, P.*, O.*
		FROM C_CART C, C_PRODUCT P, C_ORDER O 
		WHERE P.PNO = C.PNO 
		AND O.CARTNO = C.CARTNO 
		AND O.MID = 'user' AND C.CVALIDATE = 1;

