DROP TABLE C_MEMBER;
CREATE TABLE C_MEMBER(
    MNO NUMBER PRIMARY KEY,
    MID VARCHAR2(20) UNIQUE NOT NULL,
    MNAME VARCHAR2(100),
    MPW VARCHAR2(50) NOT NULL,
    MMOBILE1 CHAR(3),
    MMOBILE2 CHAR(4),
    MMOBILE3 CHAR(4),
    MEMAIL VARCHAR2(50) UNIQUE NOT NULL,
    MBIRTH CHAR(6),
    MPOST VARCHAR2(20),
    MADDR1 VARCHAR2(100),
    MADDR2 VARCHAR2(100),
    MADDR3 VARCHAR2(100),
    MREGDATE DATE
);


DROP SEQUENCE C_MEMBER_SEQ;
CREATE SEQUENCE C_MEMBER_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCACHE
NOCYCLE;

INSERT INTO C_MEMBER (MNO, MID, MNAME, MPW, MMOBILE1, MMOBILE2, MMOBILE3, MEMAIL, MBIRTH, MPOST, MADDR1, MADDR2, MADDR3, MREGDATE)
		VALUES (C_MEMBER_SEQ.NEXTVAL, 'admin', '관리자', 1111, '010', '1111', '1111', 'ljm2500@naver.com', '000101', '', '', '', '', SYSDATE);
INSERT INTO C_MEMBER (MNO, MID, MNAME, MPW, MMOBILE1, MMOBILE2, MMOBILE3, MEMAIL, MBIRTH, MPOST, MADDR1, MADDR2, MADDR3, MREGDATE)
		VALUES (C_MEMBER_SEQ.NEXTVAL, 'user1', '사용자1', 1111, '010', '1111', '1111', 'user1@fcs.com', '000101', '', '', '', '', SYSDATE);
		
		
		
		
		