DROP TABLE C_REVIEW;
CREATE TABLE C_REVIEW(
    RNO NUMBER PRIMARY KEY,
    MID VARCHAR2(20),
    PNO NUMBER,
    RTITLE VARCHAR2(100),
    RCONTENT VARCHAR2(1000),
    RFILENAME VARCHAR2 (1000),
    RSCORE NUMBER,
    RREGDATE DATE,
    CONSTRAINT REVIEW_MEMBER_FK FOREIGN KEY (MID) REFERENCES C_MEMBER (MID),
    CONSTRAINT REVIEW_PRODUCT_FK FOREIGN KEY (PNO) REFERENCES C_PRODUCT (PNO)
);

DROP SEQUENCE C_REVIEW_SEQ;
CREATE SEQUENCE C_REVIEW_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCACHE
NOCYCLE;

INSERT INTO C_REVIEW VALUES (C_REVIEW_SEQ.NEXTVAL, 'user1', 10000, '첫번째 리뷰', '상품좋아요', '', 5, SYSDATE); 
INSERT INTO C_REVIEW VALUES (C_REVIEW_SEQ.NEXTVAL, 'user1', 10000, '첫번째 리뷰', '상품좋아요', NULL, 5, SYSDATE); 
SELECT * FROM C_REVIEW;